//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearingFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountDetail
    {
        public int id { get; set; }
        public string accNum { get; set; }
        public decimal totalValue { get; set; }
        public decimal oddValue { get; set; }
        public System.DateTime modified { get; set; }
    }
}
