// <auto-generated />
namespace ClearingFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class shitwhynocreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shitwhynocreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004200300453_shit why no create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
