//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Non_Member.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long id { get; set; }
        public string accNum { get; set; }
        public string idNum { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string linkAcc { get; set; }
        public string brokerCode { get; set; }
        public Nullable<short> state { get; set; }
        public System.DateTime modified { get; set; }
        public string secAcc { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<decimal> denchinPercent { get; set; }
        public Nullable<decimal> contractFee { get; set; }
        public Nullable<decimal> pozFee { get; set; }
        public Nullable<int> memId { get; set; }
    }
}
