//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Non_Member.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class lastPrice
    {
        public int id { get; set; }
        public Nullable<int> assetid { get; set; }
        public Nullable<decimal> ePrice { get; set; }
    }
}
