//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Non_Member.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class pozit
    {
        public int id { get; set; }
        public string accNum { get; set; }
        public string side { get; set; }
        public string assetCode { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<decimal> gainLoss { get; set; }
        public Nullable<decimal> callDenchin { get; set; }
    }
}
