//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearingFramework.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public string accNum { get; set; }
        public Nullable<short> transType { get; set; }
        public Nullable<decimal> value { get; set; }
        public string note { get; set; }
        public Nullable<short> side { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> assetid { get; set; }
    }
}
